### ISSUE TITLE
Add merkle tree diff viewer (dAPI fallback page)

### ISSUE THREAD

**Issue by mcoetzee** [api3dao/dapi-management#24]

**Comment by bbenligiray** [comment]
I'm thinking of something like https://www.diffchecker.com/text-compare/ but the text is not editable. Unfortunately there doesn't seem to be an actively maintained diff package.

**Comment by mcoetzee** [comment]
Yeah I'm thinking of the same thing. I've done some initial research, and https://diff2html.xyz/ seems promising and is still actively maintained: https://github.com/rtfpessoa/diff2html
