### ISSUE TITLE
Fix the tree validation issue on DapiFallbackV2

### ISSUE THREAD

**Issue by alikonuk1** [api3dao/dapi-management#29]
The dAPI pricing Merkle tree currently supports multiple entries per dAPI name+chain ID, allowing various deviation percentages like 0.25%, 0.5%, and 1%. In the DapiFallbackV2 setup, any of these entries can be invoked while calling executeDapiFallback(). This setup may lead to discrepancies or unintended outcomes.

We need a validation that checks if there is a 1% offering in the dAPI pricing Merkle tree for all dAPIs that are listed in the dAPI fallback Merkle tree.

**Comment by BTT21000** [comment]
This is now N/A since the fallback functionality is dropped from Phase 2.1 per this [announcement](https://api3workspace.slack.com/archives/C01N6001YCE/p1701262089672769)
