### ISSUE TITLE
Add dAPI fallback executors and reverters to DapiFallbackV2

### ISSUE THREAD

**Issue by acenolaza** [api3dao/dapi-management#38]
Currently `executeDapiFallback` can be called by accounts that were granted the `Fallback executer` and a similarly `revertDapiFallback` can only be called by accounts that have the `Fallback reverter` role.

Since there is no easy way to keep track of which accounts have been granted these roles we need to replace these access control roles with a list of accounts stored in the contract like it used to be in [DapiFallbackV1](https://github.com/api3dao/manager-multisig/blob/main/chain/contracts/DapiFallbackV1.sol#L66).

An EnumerableSet.AddressSet data structure could be used here.

**Comment by BTT21000** [comment]
This issue has been added to the contract development board.
