### ISSUE TITLE
e2e tests of the FE with contracts and dapi-management

### ISSUE THREAD

**Issue by BTT21000** [api3dao/dapi-management#44]
There should be e2e tests between the FE and the way it interacts with contracts and dapi-management MTs data served through the Github Pages API.

**Comment by BTT21000** [comment]
It should be discussed whether this issue should reside on the dapi-management board or the Market FE board.

**Comment by bbenligiray** [comment]
dapi-management imo

**Comment by BTT21000** [comment]
This will firstly be done to dAPIFallbackV2 for now.
The market will have its own e2e test as per this [issue](https://github.com/api3dao/api3-market/issues/817)

**Comment by BTT21000** [comment]
> This will firstly be done for dAPIFallbackV2 for now on the dapi-management FE.

The above sentence of the [comment](https://github.com/api3dao/dapi-management/issues/44#issuecomment-1821153167) is now N/A since the fallback functionality is dropped from Phase 2.1 per this [announcement](https://api3workspace.slack.com/archives/C01N6001YCE/p1701262089672769)

It should be confirmed if this issue is still relevant since other e2e tests of the market are covered by this [issue](https://github.com/api3dao/api3-market/issues/817)

**Comment by BTT21000** [comment]
e2e tests with contracts will be done on the api3-market repo
