### ISSUE TITLE
Extend the CI to verify the Data Feed IDs and Sponsor Wallet Addresses (dAPI management)

### ISSUE THREAD

**Issue by mcoetzee** [api3dao/dapi-management#50]

**Comment by bbenligiray** [comment]
Waiting for @metobom (and I) to come up with where this information lives and how it's populated

**Comment by BTT21000** [comment]
Can leverage the script developed through PR https://github.com/api3dao/dapi-management/pull/79 for issue https://github.com/api3dao/dapi-management/issues/57

**Comment by BTT21000** [comment]
A README can be added in adding README in https://github.com/api3dao/dapi-management/tree/main/scripts/verification to document this task and related PR
