### ISSUE TITLE
Make MT page more usable with large dataset

### ISSUE THREAD

**Issue by mcoetzee** [api3dao/dapi-management#66]
- add pagination to the values table
- remove unnecessary `StandardMerkleTree.of(...)` constructors from the frontend
- prevent large tree diffs from automatically loading

**Comment by BTT21000** [comment]
Because of temporary changes listed in #82 

This issue only requires the below element:
> - remove unnecessary `StandardMerkleTree.of(...)` constructors from the frontend

For other large MT like the dAPI management MT, the FE can have have an arrow enabling the user to go back to the top of page if there are too many lines.
