### ISSUE TITLE
New script to fetch data from new gas price collection

### ISSUE THREAD

**Issue by BTT21000** [api3dao/dapi-management#90]
Create and migrate the latest MT generation script that fetches data from new gas price collection using RPC providers (initial script version is in the operations-database repo as per issue https://github.com/api3dao/tasks/issues/399 and PR https://github.com/api3dao/operations-database/pull/509) and the new version should be in the [dapi-management](https://github.com/api3dao/dapi-management) repo .

**Comment by bbenligiray** [comment]
We'll probably talk about this on today's call. Idellay the script would live in dapi-management, dapi-management wouldn't have prisma as a dependency and the user interface would be flexible, i.e. used SQL.

**Comment by BTT21000** [comment]
As discussed at the call on 11/12/23, a PostgreSQL client like pg-pool might be eventually added to the dapi-management repo to handle direct raw SQL queries.
In the meanwhile, a new repo called [data-script-examples](https://github.com/api3dao/data-script-examples) has been created as per this [comment](https://github.com/api3dao/tasks/issues/470#issuecomment-1849848363) of issue https://github.com/api3dao/tasks/issues/470 to migrate the price collector script to [data-script-examples](https://github.com/api3dao/data-script-examples).
The final price collector script will eventually be migrated to the [dapi-management](https://github.com/api3dao/dapi-management) repo and will be integrated to a larger macro script (see issue https://github.com/api3dao/dapi-management/issues/96) that does the following as per the Price MT workflow developed through these issues https://github.com/api3dao/tasks/issues/388 and https://github.com/api3dao/dapi-management/issues/77
- Copies current-hash.json into
previous-hash.json
- Populates MT values based on Pricing parameters and gas collector script outcomes
- Detects new MT values
- Regenerates root
- Clears existing signatures
- Sets the new timestamp
